name: build-app

on:
  # Add your workflow triggers here:
  # Configurable to your own desires. See https://docs.github.com/en/actions/using-workflows/triggering-a-workflow
  # Example(s) below

  # pull_request:
  #   branches: [master]

  # Same as above
  # push:
  #   branches: [master]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    uses: amedia/github-workflows/.github/workflows/node-build.yaml@master
    with:
      node-version: 18.9.0 # (i.e. 18.9.0)
      image-name: #APP_NAME (i.e. article)
      eik-publish: true
    secrets:
      gcr-serviceaccount-key: ${{ secrets.GCR_SA_KEY }}
      npm-token: ${{ secrets.NPM_TOKEN_READONLY }}
      eik-server-key: ${{ secrets.EIK_SERVER_KEY }}
      slack-bot-token: ${{ secrets.SLACK_BOT_TOKEN }}
      github-token: ${{ secrets.GITHUB_TOKEN }}
