name: init
on:
  push:
    branches:
      - master

defaults:
  run:
    shell: bash

jobs:
  init:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: ./.github/scripts/init.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
